# Generated by Django 2.2.7 on 2020-04-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password1',
            field=models.CharField(default='tloqE', max_length=6),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='password2',
            field=models.CharField(default='tloqE', max_length=6),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='vk',
            field=models.CharField(blank=True, default='2AUwe', max_length=200, null=True),
        ),
    ]
