# Generated by Django 2.2.7 on 2020-01-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='owner',
        ),
    ]
