# Generated by Django 2.2.7 on 2020-03-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200308_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='email',
            field=models.EmailField(default=' ', max_length=254, verbose_name='Ваша почта'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='vk',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
