# Generated by Django 2.2.7 on 2020-03-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200329_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Ваша почта'),
        ),
    ]
