# Generated by Django 2.2.7 on 2020-04-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200329_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='hashteg',
            field=models.CharField(default='', max_length=200, verbose_name='Место проведения'),
        ),
    ]
